name = "MeshingBenchmarks"
uuid = "508b7c1e-a04b-11e9-19af-959cc8991020"
authors = ["Steve Kelly <kd2cca@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
